version: '3'

services:
#  app:
#    build: .
#   command: npm start dev:watch
#  container_name: meu_nutri
#    ports: 
#     - '3000:3000'
#    volumes: 
#      - .:/usr/app  
  mysql:
    image: mysql
    container_name: 'databasemynutri'
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=mynutri
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password 
  mongodb:
    image: mongo:4.2
    container_name: mongodbmynutri
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: mynutri
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin     

